# Generated by Django 4.2.1 on 2023-05-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('hometown', models.CharField(max_length=300)),
                ('educational_path', models.TextField()),
                ('discipline', models.CharField(max_length=200)),
                ('compositional_principles', models.TextField()),
            ],
        ),
    ]
