# Generated by Django 4.2.1 on 2023-05-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('year_of_construction', models.DateField()),
                ('adress', models.TextField()),
                ('historical_context', models.TextField()),
                ('urban_space_transformation', models.TextField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Projects.location')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Projects.project')),
                ('gender', models.TextField(help_text='Género al que pertenece la corriente artistica del edificio')),
                ('typology', models.TextField()),
                ('current_use', models.TextField()),
                ('concept', models.TextField()),
                ('stylistic_current', models.TextField()),
            ],
            bases=('Projects.project',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt', models.CharField(max_length=300)),
                ('kind_of_element', models.CharField(choices=[('NA', 'None'), ('PLANT', 'Architectural plant'), ('FACADES', 'facades'), ('OR', 'ornaments')], max_length=200)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='UrbanSpace',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Projects.project')),
                ('role', models.TextField()),
                ('urban_policy', models.TextField(help_text='Plan urbanistico o política urbana del cual surgió (sie es parte de un plan de Gobierno, de expansión urbana u otros)')),
                ('type_of_place', models.CharField(choices=[('COL', 'Colonias'), ('PLAZAS Y PARQUES', 'Plazas y Parques'), ('VIA', 'Vialidades')], max_length=200)),
                ('special_features', models.TextField()),
                ('orientation', models.TextField()),
                ('dimensions', models.FloatField(help_text='longitud o área según sea el caso')),
                ('section', models.TextField()),
                ('urban_image_element', models.TextField()),
                ('design_princples', models.TextField()),
                ('relevance', models.TextField()),
                ('surrounding_buildings', models.ManyToManyField(to='Projects.building')),
            ],
            bases=('Projects.project',),
        ),
        migrations.AddField(
            model_name='building',
            name='surrounding_buildings',
            field=models.ManyToManyField(to='Projects.urbanspace'),
        ),
    ]
