# Generated by Django 4.2.1 on 2023-05-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biographies', '0001_initial'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_designer',
            field=models.ManyToManyField(to='Biographies.biography'),
        ),
    ]
